config/routes.rb
Rails.application.routes.draw do
  resources :projeto_duvidas
  resources :projetos do
    member do
      get "aprovar_projeto"
    end
  end
  devise_for :users
  resources :users do
    collection do
      post "registrar_via_app"
      post "autenticar_via_app"
      post "indicar"
      get "receber_indicacao"
      get "send_firebase_message"
      post "recuperar_senha"
      get "confirmar_cadastro"
      post "indicar_nao_membro"
      post "atualizar_dados"
      post "atualizar_senha"
      post "cadastrar_projeto"
      get "carregar_projetos"
      post "votar"
      post "cadastrar_duvida"
      post "responder_duvida"
      get "retornar_duvidas"
      get "carregar_p30"
      post "compartilhar_rede"
      post "remover_compartilhamento"


    end
    member do
      get "rede"
      get "atualizar_usuario"
    end
  end
  resources :categories do
    collection do
      get "add_children"
      get "atualiza_pai"
    end
  end

  root "categories#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/projeto.rb
# == Schema Information
#
# Table name: projetos
#
#  id           :bigint           not null, primary key
#  aprovado     :boolean
#  data_inicio  :datetime
#  data_termino :datetime
#  descricao    :text
#  nome         :string
#  video        :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint
#
# Indexes
#
#  index_projetos_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Projeto < ApplicationRecord
  belongs_to :user
  has_many :projeto_opcoes, class_name:"ProjetoOpcao", foreign_key: :projeto_id, primary_key: :id
  has_many :votes, through: :projeto_opcoes

  #Configuração adcional para o to_json
  def as_json(options = {})
    hash = super(options)
    hash[:data_i] = self.data_inicio.to_date.to_s
    hash[:data_f] = self.data_termino.to_date.to_s
    hash[:opcoes] =  self.projeto_opcoes
    hash[:ativo] =  Date.today >= self.data_inicio.to_date and Date.today <= self.data_termino.to_date
    hash
  end

end

app/controllers/projetos_controller.rb
class ProjetosController < ApplicationController
  before_action :set_projeto, only: [:aprovar_projeto,:show, :edit, :update, :destroy]




  # GET /projetos
  # GET /projetos.json
  def index
    @q = Projeto.ransack(params[:q])
    @projetos = @q.result.page(params[:page]).per(15)
  end

  # GET /projetos/1
  # GET /projetos/1.json
  def show
  end

  def aprovar_projeto
    @projeto.aprovado = !@projeto.aprovado
    @projeto.save
    redirect_to @projeto, notice: "Atualizado com sucesso!"
  end

  # GET /projetos/new
  def new
    @projeto = Projeto.new
  end

  # GET /projetos/1/edit
  def edit
  end

  # POST /projetos
  # POST /projetos.json
  def create
    @projeto = Projeto.new(projeto_params)

    respond_to do |format|
      if @projeto.save
        format.html { redirect_to @projeto, notice: 'Projeto was successfully created.' }
        format.json { render :show, status: :created, location: @projeto }
      else
        format.html { render :new }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projetos/1
  # PATCH/PUT /projetos/1.json
  def update
    respond_to do |format|
      if @projeto.update(projeto_params)
        format.html { redirect_to @projeto, notice: 'Projeto was successfully updated.' }
        format.json { render :show, status: :ok, location: @projeto }
      else
        format.html { render :edit }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projetos/1
  # DELETE /projetos/1.json
  def destroy
    @projeto.destroy
    respond_to do |format|
      format.html { redirect_to projetos_url, notice: 'Projeto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projeto
      @projeto = Projeto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projeto_params
      params.require(:projeto).permit(:nome, :descricao, :video, :user_id, :aprovado, :data_inicio, :data_termino)
    end
end

app/helpers/projetos_helper.rb
module ProjetosHelper
end

app/views/projetos/_form.html.erb
<%= form_with(model: projeto, local: true) do |form| %>
  <% if projeto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(projeto.errors.count, "error") %> prohibited this projeto from being saved:</h2>

      <ul>
      <% projeto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_area :descricao %>
  </div>

  <div class="field">
    <%= form.label :video %>
    <%= form.text_field :video %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :aprovado %>
    <%= form.check_box :aprovado %>
  </div>

  <div class="field">
    <%= form.label :data_inicio %>
    <%= form.datetime_select :data_inicio %>
  </div>

  <div class="field">
    <%= form.label :data_termino %>
    <%= form.datetime_select :data_termino %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projetos/edit.html.erb
<h1>Editing Projeto</h1>

<%= render 'form', projeto: @projeto %>

<%= link_to 'Show', @projeto %> |
<%= link_to 'Back', projetos_path %>

app/views/projetos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projetos</h1>

<div class="card" style="overflow: visible;">
  <div class="card-content">
    <span class="card-title grey-text text-darken-4">
      Pesquisa
    </span>
    <div id="pesquisa" class="not-show">
      <%= search_form_for @q, url: request.env['PATH_INFO'] do |f|  %>
          <%= f.text_field :nome_or_user_nome_cont, placeholder: "Projeto, Candidato" %>
          <br><br>
          <%= f.submit "Filtrar", class:"btn white-text" %>
          <%= link_to "Limpar", projetos_path, class:"btn white-text" %>
      <% end %>
    </div>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Candidato</th>
      <th>Aprovado</th>
      <th>Data início</th>
      <th>Data término</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projetos.each do |projeto| %>
      <tr>
        <td><%= projeto.nome %></td>

        <td><%= projeto.user %></td>
        <td><%= projeto.aprovado == true ? "SIM" : "NÃO" %></td>
        <td><%= projeto.data_inicio %></td>
        <td><%= projeto.data_termino %></td>
        <td><%= link_to 'Visualizar', projeto %></td>
        <td><%= link_to 'Editar', edit_projeto_path(projeto) %></td>
        <td><%= link_to 'Excluir', projeto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @projetos %>
<br>

app/views/projetos/new.html.erb
<h1>New Projeto</h1>

<%= render 'form', projeto: @projeto %>

<%= link_to 'Back', projetos_path %>

app/views/projetos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col s12">
  <div class="card">
    <div class="card-content">
      <h4>Projeto: <%= @projeto.nome %></h4>
    </div>
  </div>
  </div>
</div>

<div class="row">
  <div class="col s12 l8">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Dados</span>
        <p>
          <strong>Nome:</strong>
          <%= @projeto.nome %>
        </p>

        <p>
          <strong>Candidato:</strong>
          <%= @projeto.user %>
        </p>

        <p>
          <strong>Aprovado:</strong>
          <%= @projeto.aprovado == true ? "SIM" : "NÃO" %>
        </p>

        <p>
          <strong>Data início:</strong>
          <%= @projeto.data_inicio %>
        </p>

        <p>
          <strong>Data término:</strong>
          <%= @projeto.data_termino %>
        </p>
        <p>
          <strong>Video:</strong>
          <%= @projeto.video %>
        </p>
      </div>
    </div>
  </div>
  <div class="col s12 l4">
    <div class="card">
      <div class="card-content">
        <iframe width="auto" height="auto" src="<%= @projeto.video %>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Descrição do projeto</span>
        <p>
          <%= @projeto.descricao %>
        </p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="card">
    <div class="card-content">
      <span class="card-title">
        Opções de votação
      </span>
      <table>
        <thead>
        <th>Opção</th>
        <th>Votos</th>
        </thead>
      <% @projeto.projeto_opcoes.each do |op| %>
          <tr>
            <td><%= op %></td>
            <td><%= op.total_votos %></td>
          </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12">
      <%= link_to "Aprovar Projeto", aprovar_projeto_projeto_path(@projeto), class:"btn white-text" if !@projeto.aprovado %>
    <%= link_to "Reprovar Projeto", aprovar_projeto_projeto_path(@projeto), class:"btn white-text" if @projeto.aprovado %>
  </div>
</div>


<%= link_to 'Projetos', projetos_path %>