config/routes.rb
Rails.application.routes.draw do
  resources :projeto_duvidas
  resources :projetos do
    member do
      get "aprovar_projeto"
    end
  end
  devise_for :users
  resources :users do
    collection do
      post "registrar_via_app"
      post "autenticar_via_app"
      post "indicar"
      get "receber_indicacao"
      get "send_firebase_message"
      post "recuperar_senha"
      get "confirmar_cadastro"
      post "indicar_nao_membro"
      post "atualizar_dados"
      post "atualizar_senha"
      post "cadastrar_projeto"
      get "carregar_projetos"
      post "votar"
      post "cadastrar_duvida"
      post "responder_duvida"
      get "retornar_duvidas"
      get "carregar_p30"
      post "compartilhar_rede"
      post "remover_compartilhamento"


    end
    member do
      get "rede"
      get "atualizar_usuario"
    end
  end
  resources :categories do
    collection do
      get "add_children"
      get "atualiza_pai"
    end
  end

  root "categories#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  active                 :boolean
#  admin                  :boolean
#  ancestry               :string
#  cidade                 :string
#  cidade_votacao         :string
#  codigo_indicacao       :string
#  cpf                    :string
#  data_nascimento        :date
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  estado                 :string
#  estado_votacao         :string
#  genero                 :string
#  indicador              :integer
#  nome                   :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  telefone               :string
#  texto_candidato        :text
#  video_candidato        :text
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  category_id            :bigint
#  compartilhado_id       :integer
#
# Indexes
#
#  index_users_on_ancestry              (ancestry)
#  index_users_on_category_id           (category_id)
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#

class User < ApplicationRecord
  require 'rest-client'
  has_ancestry
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :category, optional: true
  has_many :projetos

  validates :email,:cpf, uniqueness: true
  validates :nome, :data_nascimento, :genero,:telefone,:cidade,:estado, :cidade_votacao, :estado_votacao, presence: true

  before_create :set_categoria_eleitor

  after_create :verifica_indicacao
  after_create :cria_usuario_social


  def compartilhar_socify(p30,follow)
    begin
      membros = self.descendant_ids
      result = RestClient.post 'http://mandato-socify.herokuapp.com/users/compartilhar_rede', {follow: follow, user: self.id, p30: p30, membros: membros}
    rescue
    end

  end

  def cria_usuario_social
      result = RestClient.post 'http://mandato-socify.herokuapp.com/users/create_mantado_user', {user: JSON.parse(self.to_json)}
  end

  def seguir_rede
  rede = self.ancestors.pluck(:id)
  result = RestClient.post 'http://mandato-socify.herokuapp.com/users/seguir_rede', {cpf: self.cpf, membros: rede}
  end

  def self.atualizar_usuarios
    User.where(estado_votacao: nil).each do |u|
      begin
      u.estado_votacao = u.estado
      u.cidade_votacao = u.cidade
      u.active = true
      u.save
      rescue
      end
    end
  end

  #Método que notifica os p30 sobre eleitores sem rede na sua zona
  def self.eleitores_sem_rede
    User.where(indicador: nil).group_by(&:cidade_votacao).map do |cidade, users|
      p30 = User.joins(:category).where("categories.namespace ilike 'P30' ").where(cidade_votacao: cidade)
      p30.each do |p|
        UserMailer.with(user: p, eleitores: users).eleitores_sem_rede.deliver_later
      end
    end

  end

  #Método que verifica se existe alguma indicação para o novo membro
  def verifica_indicacao
    if self.codigo_indicacao.present?
      begin
        indicacao = Indication.find_by(codigo: self.codigo_indicacao)
        if indicacao.present? and !indicacao.status
          indicador = indicacao.user
          categoria = indicador.category
          categoria_filha = categoria.children.where(active: true).first

          self.indicador = indicador.id
          self.parent = indicador
          if categoria_filha.present?
            self.category = categoria_filha
          else
            self.category = categoria
          end

          if self.save
            indicacao.update(status: true)
          end
        end
      rescue

      end
    end
  end

  #Seta a categoria eleitor para o primeiro cadastro
  def set_categoria_eleitor
    if !self.category.present?
      self.category = Category.find_by(namespace: "eleitor")
    end
  end

  #Configuração adcional para o to_json
  def as_json(options = {})
    hash = super(options)
    hash[:categoria_nome] =  self.category.present? ? self.category.name : "Sem Categoria"
    hash[:categoria_topico] =  self.category.present? ? self.category.namespace : "eleitor"
    hash
  end

  #Retorna o nome do usuário
  def to_s
    self.nome
  end

  #Verifica se o usuário tem permissão para logar
  def active_for_authentication?
    super and self.admin
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'fcm'
  skip_before_action :verify_authenticity_token

  before_action :allow_iframe, :set_headers
  before_action :authenticate_user!, except: [:remover_compartilhamento,:compartilhar_rede,:carregar_p30,:retornar_duvidas,:responder_duvida,:cadastrar_duvida,:votar,:carregar_projetos,:cadastrar_projeto,:atualizar_dados, :indicar_nao_membro,:confirmar_cadastro,:registrar_via_app, :autenticar_via_app,:indicar,:receber_indicacao,:recuperar_senha]
  before_action :set_user, only: [:show, :edit, :update, :destroy,:rede,:atualizar_usuario]
  before_action :set_combos, only: [:new,:edit,:update,:create]


  #Método utilizado para desfazer o compartilhamento da rede
  def remover_compartilhamento
    user = User.find_by_cpf(params[:cpf])
    user.parent = nil
    user.compartilhar_socify(user.compartilhado_id,false)
    user.compartilhado_id = nil
    if user.save
      render json: {status: "OK", msg: "O compartilhamento foi removido", compartilhado_id: 0, compartilhado_nome: ""}
    else
      render json: {status: "ERROR", msg: user.errors.full_message.to_sentence}
    end
  end

  #Método utlizado para compartilhar a rede do candidato
  def compartilhar_rede
    user = User.find_by_cpf(params[:cpf])
    p30_selecionado = JSON.parse(params[:p30])
    p30 = User.find(p30_selecionado["id"])
    user.parent = p30
    user.compartilhado_id = p30.id
    if user.save
      user.compartilhar_socify(p30.id,true)
      render json: {status: "OK", msg: "Sua rede foi compartilhada com #{p30.nome}", compartilhado_id: p30.id, compartilhado_nome: p30.nome}
    else
      render json: {status: "ERROR", msg: user.errors.full_message.to_sentence}
    end
  end

  #Método que retorna os p30 para o compartilhamento de rede
  def carregar_p30
    users = User.includes(:category).where(categories: {namespace:  "p30"}).where.not(cpf: params[:cpf])
    render json: {status: "OK", p30: users}
  end

  #Método que retorna as dúvidas do projeto
  def retornar_duvidas
    duvidas = ProjetoDuvida.where(projeto_id: params[:projeto])
    render json: {status: "OK", duvidas: duvidas}
  end

  #Método para criar a dúvida do projeto
  def cadastrar_duvida
    user = User.find_by_cpf(params[:cpf])
    duvida = ProjetoDuvida.new(duvida_params)
    duvida.user = user
    duvida.resposta = ""
    if duvida.save
      render json: {status: "OK", msg: "Dúvida enviada com sucesso.", duvida: duvida}
    else
      render json: {status: "ERROR", msg: duvida.errors.full_message.to_sentence }
    end

  end

  #Método utilizado para responder a dúvida
  def responder_duvida
    duvida = ProjetoDuvida.find(params[:id])
    if duvida.update(duvida_params)
      duvidas = ProjetoDuvida.where(projeto_id: duvida.projeto_id)
      render json: {status: "OK", msg: "Resposta enviada com sucesso.", duvidas: duvidas}
    else
      render json: {status: "ERROR", msg: duvida.errors.full_message.to_sentence }
    end


  end


  #Método que atualiza os dados cadastrais
  def atualizar_dados
    #binding.pry
    @user = User.find_by_cpf(params[:cpf])
    if @user.update(user_params2)
      render json: {status: "OK", msg: "Dados atualizados com sucesso!"}
    else
      render json: {status: "error", msg: @user.errors}
    end
  end

  #método utilizado para realizar a votação no projeto
  def votar
    user = User.find_by_cpf(params[:cpf])
    opcao = ProjetoOpcao.find(params[:opcao])
    votou = ProjetoUser.where(user: user, projeto_id: opcao.projeto_id).last

    if votou.present?
      render json: {status: "ERROR", msg: "Você já votou neste projeto!"}
    else
      Vote.create(projeto_opcao_id: opcao.id)
      ProjetoUser.create(user_id: user.id, projeto_id: opcao.projeto_id)
      render json: {status: "OK", msg:"Voto realizado com sucesso!"}
    end


  end


  #Métoo carrega os projetos
  def carregar_projetos
    user = User.find_by_cpf(params[:cpf])
    if params[:tipo] == "p30"
      projetos = Projeto.where(user: user)
    else
      if user.root.category.namespace == "p30"
        projetos = Projeto.where(user: user.root, aprovado: true)
      else
        projetos = []
      end

    end

    render json: {status:"OK",projetos: projetos}


  end


  #Método que confirma o cadastro por email do usuário
  def confirmar_cadastro
      user = User.find(params[:code])
      user.active = true
      user.save
      render layout: "clean"
  end


  #Método que envia uma nova senha para o email do usuário
  def recuperar_senha
    user = User.find_by_cpf(params[:cpf])
    if user.present?
      nova_senha = (0...6).map { rand(10) }.join
      user.password = nova_senha
      user.password_confirmation = nova_senha
      if user.save
        UserMailer.enviar_senha(nova_senha,user).deliver
        render json: {status:"OK", msg: "Um e-mail com sua nova senha foi enviado para #{user.email}"}
      else
        render json: {status:"ERROR", msg: user.errors.full_messages.to_sentence}
      end
    else
      render json: {status:"ERROR", msg: "Usuário não encontrado"}
    end


  end

  #Envia o push notification
  def send_firebase_message
    fcm = FCM.new("AAAAuKwVM2c:APA91bEqwWboRl9cPyAdkp20oIu_Jgh8OPbfgJprsmydAiGrAJVrUUhYOvCulEfV5-TVI4tMMBzDlxxQvvv_otKezPvZoH-cy06p99zqIeOEkWUmyDoupMscs27_0R6OMwbs2wIVfOdT")
    options = { "notification": {
        "title": params[:titulo],
        "body": params[:msg]
    }
    }
    response = fcm.send_to_topic(params[:topico], options)
    redirect_to users_path, notice: "Notificação enviada com sucesso."
  end

  # GET /users
  # GET /users.json
  def index
    @q = User.ransack(params[:q])
    @users = @q.result.page(params[:page]).per(15)
    @topicos = Category.all.map{|a| [a.name,a.namespace]}
    @topicos << ["Geral","geral"]
  end

  def allow_iframe
    response.headers.except! 'X-Frame-Options'
  end

  def set_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'GET'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
  end


  #Método utilizado pra realizar o cadastro de um projeto para votação
  def cadastrar_projeto
    #binding.pry
    user = User.find_by_cpf(params[:cpf])
    projeto = Projeto.new(user: user)
    projeto.aprovado = false
    projeto.data_inicio = params[:data_inicio]
    projeto.data_termino = params[:data_termino]
    projeto.descricao = params[:descricao]
    projeto.nome = params[:nome]
    projeto.video = params[:video]
    if projeto.save
      opcoes = JSON.parse(params[:opcoes])
      opcoes.each do |o|
        ProjetoOpcao.create(projeto: projeto, votos: 0, nome: o["opcao"])
      end
      render json: {status: "OK", projeto: projeto, msg: "Projeto cadastrado com sucesso!"}
    else
      render json: {status: "ERROR", msg: projeto.errors.full_messages.to_sentence}
    end

  end

  #Método utilizado para registrar o usuário pelo app
  def registrar_via_app

    categoria = Category.find_by_namespace(params[:tipo])
    user = User.new(codigo_indicacao: params[:indicacao], cidade_votacao: params[:cidade_votacao], estado_votacao: params[:estado_votacao],cidade: params[:cidade], estado: params[:estado],telefone: params[:telefone],category_id: categoria.id, nome: params[:nome], cpf: params[:cpf], email: params[:email], genero: params[:genero], data_nascimento: params[:data_nascimento], password: params[:password], password_confirmation:params[:password_confirmation])
    user.active = false
    #binding.pry
    if user.save
      UserMailer.with(user: user).confirmar_cadastro.deliver_later
      render json: {status: "OK", user: user}
    else
      render json: {status: "ERROR", msg: user.errors.full_messages.to_sentence}
    end

  end

  #Método utilizado para autenticar pelo app'
  def autenticar_via_app
    user = User.find_by(cpf: params[:cpf])

    if user.present? and user.active
      if user.valid_password? params[:password]
        if user.root != user
          render json: {texto_candidato: user.texto_candidato,video_candidato: user.video_candidato,status: "OK", user: user, qtd_membros: user.root.descendants.size, qtd_abaixo: user.descendants.size, qtd_cidade: User.where(cidade: user.cidade).count, candidato: user.root.category.namespace == "p30" ? user.root.nome : "Sem Candidato"}
        else
          render json: {texto_candidato: user.texto_candidato,video_candidato: user.video_candidato,status: "OK", user: user, qtd_membros: user.root.descendants.size, qtd_abaixo: user.descendants.size, qtd_cidade: User.where(cidade: user.cidade).count, candidato: user.category.namespace == "p30" ? user.nome : "Sem Candidato"}
        end

      else
        render json: {status: "ERROR"}
      end
    else
      render json: {status: "ERROR"}
    end

  end

  #Método utilizado para criar a indicação
  def indicar

    if !(params[:cpf_indicador] == params[:cpf_indicado])
      indicador = User.find_by(cpf: params[:cpf_indicador])
      indicado = User.find_by(cpf: params[:cpf_indicado])
      if indicador.category.present?
        if User.where(indicador: indicador.id).count < indicador.category.max
          if !indicado.present?
            render json: {status: "ERROR", msg:"Indicado precisa estar cadastrado antes de realizar a indicação."}
          else
            if indicado.category.present? and indicador.category.child_of?(indicado.category)#Verifica se o indicado já possui uma categoria superiror ao indicador
              render json: {status: "ERROR", msg: "Indicado pertence a uma categoria superior."}
            else
              indication = Indication.new
              indication.user = indicador
              indication.indicado = indicado.id
              indication.latitude = params[:latitude]
              indication.longitude = params[:longitude]
              indication.status = false
              if indication.save

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(url: atualizar_usuario_user_path,method: :get, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, value: @user.nome %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf, value: @user.cpf %>
  </div>

    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email, value: @user.email %>
    </div>

  <div class="field">
    <%= form.label :data_nascimento, "Data de Nascimento" %>
    <%= form.text_field :data_nascimento,{value: @user.data_nascimento, class:"datepicker2"} %>
  </div>

  <div class="input-field">

    <%= form.select :genero, options_for_select([["Masculino","masculino"],["Feminino","feminino"]], @user.genero) %>
    <%= form.label :genero, "Gênero" %>
  </div>

  <div class="input-field">

    <%= form.select :category_id, options_for_select(@categorias, @user.category_id), {include_blank: true} %>
    <%= form.label :category_id, "Categoria" %>
  </div>

  <div class="field">
    <%= form.label :indicador %>
    <%= form.select :indicador, options_for_select(@usuarios,@user.indicador), {include_blank: true},{ class:"browser-default select2"} %>
  </div>

  <div class="actions">
    <%= form.submit "Salvar", target: "_self"%>
  </div>
<% end %>

app/views/users/confirmar_cadastro.html.erb
<div class="center-align"><img src="/images/mandato_logo.jpeg" alt=""></div>
<div class="row center-align">
  <h1>Cadastro confirmado com sucesso!</h1>
</div>

app/views/users/edit.html.erb
<h1 class="center-align">Editar Usuário</h1>

<%= render 'form', user: @user %>


<%= link_to 'Usuários', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="center-align">Pessoas</h1>

<div class="card">
  <div class="card-content">
  <%= search_form_for @q do |f| %>

      <div class="input-field">
        <%= f.label :nome_or_category_name_or_cpf_cont, "Nome, Categoria ou CPF" %>
        <%= f.search_field :nome_or_category_name_or_cpf_cont %>
      </div>

      <%= f.submit "Pesquisar" %>
  <% end %>
  </div>
</div>

<div class="card">
  <div class="card-content">
    <a class="waves-effect waves-light btn modal-trigger" href="#modal1">Enviar Notificação</a>
<table class="striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>CPF</th>
      <th>Email</th>
      <th>Data de nascimento</th>

      <th>Categoria</th>
      <th>Indicador</th>
      <th>Naturalidade</th>
      <th>Local de Votação</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nome %></td>
        <td><%= user.cpf %></td>
        <td><%= user.email %></td>
        <td><%= user.data_nascimento %></td>

        <td><%= user.category %></td>
        <td><%= user.parent %></td>
        <td><%= user.cidade %> - <%= user.estado %></td>
        <td><%= user.cidade_votacao %> - <%= user.estado_votacao %></td>
        <td></td>
        <td><%= link_to 'Rede', rede_user_path(user), target: "_self"  %> |
          <%= link_to 'Editar', edit_user_path(user) , target: "_self"%></td>
        <!--<td></td>-->
        <!--<td><%#= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

    <div id="modal1" class="modal">
      <%= form_with url: send_firebase_message_users_path, method: :get, local: true do | form| %>
        <div class="modal-content">
          <h4>Envio de Notificação</h4>
          <div class="input-field">
            <%= form.label :titulo, "Título" %>
            <%= form.text_field :titulo %>
          </div>

          <div class="input-field">
            <%= form.label :msg, "Mensagem" %>
            <%= form.text_area :msg, {class:"materialize-textarea"} %>
          </div>

          <div class="input-field">

            <%= form.select :topico, @topicos %>
            <%= form.label :topico, "Para" %>
          </div>
        </div>
        <div class="modal-footer">
          <%= form.submit "Enviar", class:"btn white-text", target: "_self" %>
        </div>
      <% end %>
    </div>

<%= paginate @users %>

<br>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/receber_indicacao.html.erb
<div class="center-align"><img src="/images/mandato_logo.jpeg" alt=""></div>
<div class="row center-align">
  <% if @sucesso %>
    <h1>Indicação ativada com sucesso!</h1> <br>
    <h4>Agora você é um <%= @indicado.category %></h4>
  <% else %>
      <h1>Erro ao ativar indicação!</h1> <br>
  <% end %>
</div>

app/views/users/rede.html.erb
<p id="notice"><%= notice %></p>

<h1 class="center-align">Pessoas</h1>

<div class="card-panel">
  <b>Pessoa: </b><%= @user %> <br>
  <b>Categoria: </b><%= @user.category %>
</div>

<div class="card">

  <div class="card-content">
    <span class="card-title">Rede</span>
    <table>
      <thead>
      <tr>
        <th>Nome</th>
        <th>CPF</th>
        <th>Data de nascimento</th>
        <th>Gênero</th>
        <th>Categoria</th>
        <th>Indicador</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @user.descendants.each do |user| %>
          <tr>
            <td><%= user.nome %></td>
            <td><%= user.cpf %></td>
            <td><%= user.data_nascimento %></td>
            <td><%= user.genero %></td>
            <td><%= user.category %></td>
            <td><%= user.parent %></td>
            <td><%= link_to 'Rede', rede_user_path(user), target: "_self" %></td>
            <!--<td><%#= link_to 'Edit', edit_user_path(user) %></td>-->
            <!--<td><%#= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>


<br>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @user.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @user.cpf %>
</p>

<p>
  <strong>Data nascimento:</strong>
  <%= @user.data_nascimento %>
</p>

<p>
  <strong>Genero:</strong>
  <%= @user.genero %>
</p>

<p>
  <strong>Category:</strong>
  <%= @user.category %>
</p>

<p>
  <strong>Indicador:</strong>
  <%= @user.indicador %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>