config/routes.rb
Rails.application.routes.draw do
  resources :projeto_duvidas
  resources :projetos do
    member do
      get "aprovar_projeto"
    end
  end
  devise_for :users
  resources :users do
    collection do
      post "registrar_via_app"
      post "autenticar_via_app"
      post "indicar"
      get "receber_indicacao"
      get "send_firebase_message"
      post "recuperar_senha"
      get "confirmar_cadastro"
      post "indicar_nao_membro"
      post "atualizar_dados"
      post "atualizar_senha"
      post "cadastrar_projeto"
      get "carregar_projetos"
      post "votar"
      post "cadastrar_duvida"
      post "responder_duvida"
      get "retornar_duvidas"
      get "carregar_p30"
      post "compartilhar_rede"
      post "remover_compartilhamento"


    end
    member do
      get "rede"
      get "atualizar_usuario"
    end
  end
  resources :categories do
    collection do
      get "add_children"
      get "atualiza_pai"
    end
  end

  root "categories#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/projeto_duvida.rb
# == Schema Information
#
# Table name: projeto_duvidas
#
#  id         :bigint           not null, primary key
#  duvida     :text
#  resposta   :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  projeto_id :bigint
#  user_id    :bigint
#
# Indexes
#
#  index_projeto_duvidas_on_projeto_id  (projeto_id)
#  index_projeto_duvidas_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (projeto_id => projetos.id)
#  fk_rails_...  (user_id => users.id)
#

class ProjetoDuvida < ApplicationRecord
  belongs_to :projeto
  belongs_to :user

  #Configuração adcional para o to_json
  def as_json(options = {})
    hash = super(options)
    hash[:usuario] = self.user.nome
    hash
  end
end

app/controllers/projeto_duvidas_controller.rb
class ProjetoDuvidasController < ApplicationController
  before_action :set_projeto_duvida, only: [:show, :edit, :update, :destroy]

  # GET /projeto_duvidas
  # GET /projeto_duvidas.json
  def index
    @projeto_duvidas = ProjetoDuvida.all
  end

  # GET /projeto_duvidas/1
  # GET /projeto_duvidas/1.json
  def show
  end

  # GET /projeto_duvidas/new
  def new
    @projeto_duvida = ProjetoDuvida.new
  end

  # GET /projeto_duvidas/1/edit
  def edit
  end

  # POST /projeto_duvidas
  # POST /projeto_duvidas.json
  def create
    @projeto_duvida = ProjetoDuvida.new(projeto_duvida_params)

    respond_to do |format|
      if @projeto_duvida.save
        format.html { redirect_to @projeto_duvida, notice: 'Projeto duvida was successfully created.' }
        format.json { render :show, status: :created, location: @projeto_duvida }
      else
        format.html { render :new }
        format.json { render json: @projeto_duvida.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projeto_duvidas/1
  # PATCH/PUT /projeto_duvidas/1.json
  def update
    respond_to do |format|
      if @projeto_duvida.update(projeto_duvida_params)
        format.html { redirect_to @projeto_duvida, notice: 'Projeto duvida was successfully updated.' }
        format.json { render :show, status: :ok, location: @projeto_duvida }
      else
        format.html { render :edit }
        format.json { render json: @projeto_duvida.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projeto_duvidas/1
  # DELETE /projeto_duvidas/1.json
  def destroy
    @projeto_duvida.destroy
    respond_to do |format|
      format.html { redirect_to projeto_duvidas_url, notice: 'Projeto duvida was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projeto_duvida
      @projeto_duvida = ProjetoDuvida.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projeto_duvida_params
      params.require(:projeto_duvida).permit(:projeto_id, :duvida, :resposta, :user_id)
    end
end

app/helpers/projeto_duvidas_helper.rb
module ProjetoDuvidasHelper
end

app/views/projeto_duvidas/_form.html.erb
<%= form_with(model: projeto_duvida, local: true) do |form| %>
  <% if projeto_duvida.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(projeto_duvida.errors.count, "error") %> prohibited this projeto_duvida from being saved:</h2>

      <ul>
      <% projeto_duvida.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :projeto_id %>
    <%= form.text_field :projeto_id %>
  </div>

  <div class="field">
    <%= form.label :duvida %>
    <%= form.text_area :duvida %>
  </div>

  <div class="field">
    <%= form.label :resposta %>
    <%= form.text_area :resposta %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projeto_duvidas/edit.html.erb
<h1>Editing Projeto Duvida</h1>

<%= render 'form', projeto_duvida: @projeto_duvida %>

<%= link_to 'Show', @projeto_duvida %> |
<%= link_to 'Back', projeto_duvidas_path %>

app/views/projeto_duvidas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projeto Duvidas</h1>

<table>
  <thead>
    <tr>
      <th>Projeto</th>
      <th>Duvida</th>
      <th>Resposta</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projeto_duvidas.each do |projeto_duvida| %>
      <tr>
        <td><%= projeto_duvida.projeto %></td>
        <td><%= projeto_duvida.duvida %></td>
        <td><%= projeto_duvida.resposta %></td>
        <td><%= projeto_duvida.user %></td>
        <td><%= link_to 'Show', projeto_duvida %></td>
        <td><%= link_to 'Edit', edit_projeto_duvida_path(projeto_duvida) %></td>
        <td><%= link_to 'Destroy', projeto_duvida, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Projeto Duvida', new_projeto_duvida_path %>

app/views/projeto_duvidas/new.html.erb
<h1>New Projeto Duvida</h1>

<%= render 'form', projeto_duvida: @projeto_duvida %>

<%= link_to 'Back', projeto_duvidas_path %>

app/views/projeto_duvidas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Projeto:</strong>
  <%= @projeto_duvida.projeto %>
</p>

<p>
  <strong>Duvida:</strong>
  <%= @projeto_duvida.duvida %>
</p>

<p>
  <strong>Resposta:</strong>
  <%= @projeto_duvida.resposta %>
</p>

<p>
  <strong>User:</strong>
  <%= @projeto_duvida.user %>
</p>

<%= link_to 'Edit', edit_projeto_duvida_path(@projeto_duvida) %> |
<%= link_to 'Back', projeto_duvidas_path %>