config/routes.rb
Rails.application.routes.draw do
  resources :projeto_duvidas
  resources :projetos do
    member do
      get "aprovar_projeto"
    end
  end
  devise_for :users
  resources :users do
    collection do
      post "registrar_via_app"
      post "autenticar_via_app"
      post "indicar"
      get "receber_indicacao"
      get "send_firebase_message"
      post "recuperar_senha"
      get "confirmar_cadastro"
      post "indicar_nao_membro"
      post "atualizar_dados"
      post "atualizar_senha"
      post "cadastrar_projeto"
      get "carregar_projetos"
      post "votar"
      post "cadastrar_duvida"
      post "responder_duvida"
      get "retornar_duvidas"
      get "carregar_p30"
      post "compartilhar_rede"
      post "remover_compartilhamento"


    end
    member do
      get "rede"
      get "atualizar_usuario"
    end
  end
  resources :categories do
    collection do
      get "add_children"
      get "atualiza_pai"
    end
  end

  root "categories#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :bigint           not null, primary key
#  name        :string
#  description :string
#  max         :integer
#  active      :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  ancestry    :string
#  namespace   :string
#
# Indexes
#
#  index_categories_on_ancestry  (ancestry)
#

class Category < ApplicationRecord
  has_ancestry



  #Imprime o nome da categoria
  def to_s
    self.name
  end


  #Desativa os outros filhos do pai
  def desativar_filhos
    pai = self.parent
    if self.active == true
      Category.where(id: pai.child_ids).update_all(active: false)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController


  before_action :authenticate_user!
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all#.where(active: true)
  end



  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new(active: true)
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Categoria cadastrada com sucesso.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  #Adiciona uma catogia filha
  def add_children
    categoria = Category.find(params[:category_id])
    Category.where(id: categoria.child_ids).update_all(active: false)
    categoria.children.create name: params[:name], description: params[:description], max: params[:max], active: params[:active]
    redirect_to categories_path
  end

  #Atualiza o pai da categoria selecionada
  def atualiza_pai
    categoria_filha = Category.find(params[:categoria_filha])
    categoria_pai = Category.find(params[:categoria_pai])
    categoria_filha.update_attribute :parent, categoria_pai
    redirect_to categories_path
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    #binding.pry
    pai = @category.parent
    #if pai.present?
    #if params[:category][:active].present? and params[:category][:active] == "1"
     # Category.where(id: pai.child_ids).update_all(active: false)
    #end
    #end
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Categoria atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Categoria excluída com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :max, :active,:namespace)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= form.label :name, "Nome" %>
    <%= form.text_field :name %>
  </div>

  <div class="input-field">
    <%= form.label :description, "Descrição" %>
    <%= form.text_area :description, {class:"materialize-textarea"} %>
  </div>

  <div class="input-field">
    <%= form.label :max, "Total de indicações" %>
    <%= form.number_field :max %>
  </div>

  <div class="field">

    <%= form.check_box :active %>
    <%= form.label :active, "Ativo" %>
  </div>

    <div class="input-field">
      <%= form.label :namespace, "Tópico de Notificação" %>
      <%= form.text_field :namespace %>
    </div>

    <br>

  <div class="actions">
    <%= form.submit "Salvar", class:"btn white-text", target:"_self" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="center-align">Editar Categoria</h1>

<%= render 'form', category: @category %>

<%= link_to 'Categorias', categories_path, target:"_self" %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="center-align">Categorias</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Categoria Pai</th>
      <th>Tópico</th>
      <th>Ativa</th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name, category %></td>
        <td><%= category.parent %></td>
        <td><%= category.namespace %></td>
        <td><%= category.active == true ? "SIM" : "NÃO" %></td>

        <td>

            <%= link_to "Novo Filho", "#modal1", class:"modal-trigger", target:"_self", onclick:"set_id(#{category.id})" %><!--if !category.has_children?-->
          <%= link_to "Alterar Pai", "#modal_pai", class:"modal-trigger", target:"_self", onclick:"set_id(#{category.id})" %>
            <%= link_to "Editar", edit_category_path(category), target:"_self" %>

            <%= link_to 'Excluir', category, method: :delete, data: { confirm: 'Deseja realmente excluir?' } %>

        </td>




      </tr>
    <% end %>
  </tbody>
</table>






<!-- Modal Structure -->
<div id="modal1" class="modal">
  <div class="modal-content">
    <h4>Categoria Filha</h4>
    <%= form_with url: add_children_categories_path, method: :get, local: true do |form| %>
        <%= form.hidden_field :category_id, id:"categoria" %>
        <div class="input-field">
          <%= form.label :name, "Nome" %>
          <%= form.text_field :name %>
        </div>

        <div class="input-field">
          <%= form.label :description, "Descrição" %>
          <%= form.text_area :description, {class:"materialize-textarea"} %>
        </div>

        <div class="input-field">
          <%= form.label :max, "Total de indicações" %>
          <%= form.number_field :max %>
        </div>

        <div class="field">

          <%= form.check_box :active %>
          <%= form.label :active, "Ativo" %>
        </div>
        <%= form.submit "Salvar", class:"btn white-text", target:"_self"%>
    <% end %>
  </div>
  <div class="modal-footer">
    <!--<a href="#!" class="modal-close waves-effect waves-green btn-flat">Agree</a>-->
  </div>
</div>

<div id="modal_pai" class="modal">
  <div class="modal-content">
    <h4>Atualizar Categoria Pai</h4>
    <%= form_with url: atualiza_pai_categories_path, method: :get, local: true do |form| %>
        <%= form.hidden_field :categoria_filha, id:"categoria_filha" %>
        <div class="input-field">

          <%= form.select :categoria_pai, @categories.map{|a| [a.name,a.id] } %>
          <%= form.label :categoria_pai, "Categoria Pai" %>
        </div>

        <%= form.submit "Salvar", class:"btn white-text", target:"_self"%>
    <% end %>
  </div>
  <div class="modal-footer">
    <!--<a href="#!" class="modal-close waves-effect waves-green btn-flat">Agree</a>-->
  </div>
</div>

<br>

<%= link_to 'Nova Categoria', new_category_path, class:"btn white-text", target:"_self" %>

<script type="text/javascript" charset="utf-8">


 function set_id(id)
 {
    $("#categoria").val(id);
     $("#categoria_filha").val(id);
 }
</script>

app/views/categories/new.html.erb
<h1 class="center-align">Nova Categoria</h1>

<%= render 'form', category: @category %>

<%= link_to 'Voltar', categories_path , target:"_self"%>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<p>
  <strong>Max:</strong>
  <%= @category.max %>
</p>

<p>
  <strong>Active:</strong>
  <%= @category.active %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>